# Default Profile
[profile.default]
cache_path = 'cache_forge'
libs = ['node_modules', 'lib']
optimizer = true
optimizer-runs = 1_000
out = 'out'
remappings = []
solc-version = "0.8.19"
src = 'contracts'
test = 'test/foundry'

# Gas reporting
gas_reports = [
  "ContractFactory",
  "Registry",
  "Allo",
  "RFPSimpleStrategy",
  "RFPCommitteeStrategy",
  "QVSimpleStrategy",
  "DonationVotingMerkleDistributionDirectTransferStrategy",
  "DonationVotingMerkleDistributionVaultStrategy",
  "QVImpactStreamStrategy",
  "RecipientSuperApp",
  "SuperAppBaseSQF",
  "SQFSuperFluidStrategy",
]
gas_reports_ignore = [
  "TestStrategy",
  "QVBaseStrategyTestMock",
  "Permit2",
  "MockStrategy",
]

# Storage layout compatibility 
build_info = true
extra_output = ["storageLayout"]
# Grants access to solc
allow_paths = ['node_modules']

[fmt]
ignore = ['contracts/strategies/_poc/qv-hackathon/SchemaResolver.sol']

[rpc_endpoints]
arbitrumOne = "${ARBITRUM_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
opgoerli = "${OPGOERLI_RPC_URL}"
